"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "")
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY must be set in the environment")

_allowed = os.environ.get("ALLOWED_HOSTS", "")
if _allowed:
    ALLOWED_HOSTS = _allowed.split(",")
else:
    ALLOWED_HOSTS = []

# URL of the FCS counting service (see counter/ and docker-compose.yml).
COUNTER_URL = os.environ.get("COUNTER_URL", "http://counter:8001/count")

# Shared secret sent as X-Service-Token to all three analysis services. One token
# rather than three: if it leaks all three are exposed, but there is one value to
# rotate. Deliberately not required here — the boundary is enforced by the services,
# which refuse to boot without it, so a missing value fails loudly as a 401 at
# upload time instead of blocking `runserver`/`manage.py test`.
SERVICE_TOKEN = os.environ.get("SERVICE_TOKEN", "")

# How long the portal waits on each analysis service. Each service's own gunicorn
# --timeout (GUNICORN_TIMEOUT in its container) must stay *above* the matching value
# here, so a slow analysis is reported by the service rather than guessed at by the
# client — see the table in README.
COUNTER_TIMEOUT = int(os.environ.get("COUNTER_TIMEOUT", "180"))
STRAIN_TIMEOUT = int(os.environ.get("STRAIN_TIMEOUT", "600"))
# Microscopy gets the most headroom: a freshly started service pays a
# 1.2 GB checkpoint load before inference begins.
MICRO_TIMEOUT = int(os.environ.get("MICRO_TIMEOUT", "600"))

# URL of the microscopy (Cellpose) analysis service (see microscopy/ and docker-compose.yml).
MICRO_URL = os.environ.get("MICRO_URL", "http://microscopy:8002/micro")

# URL of the strain-composition aligner (see strain_composition/ and docker-compose.yml).
STRAIN_URL = os.environ.get("STRAIN_URL", "http://strain:8003/strain_comp")


# Application definition

INSTALLED_APPS = [
    # portal first so its templates/registration/ overrides the copies that ship
    # with django.contrib.admin (the app-dirs loader takes the first match).
    "portal",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Log in by email (EmailBackend), but keep the default username backend so the
# /admin superuser login still works.
AUTHENTICATION_BACKENDS = [
    "portal.auth.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Where LoginRequiredMiddleware sends unauthenticated users.
LOGIN_URL = "portal:signin"

# Invite links are password-reset links, so they expire on this timer.
PASSWORD_RESET_TIMEOUT = 3 * 24 * 60 * 60  # 3 days

# Absolute base URL, used by `manage.py invite` to build the link it prints.
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000").rstrip("/")

# Email (password-reset / invite links). Set EMAIL_HOST and the backend
# switches to SMTP automatically; unset, it prints to the log (dev default).
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "LabPortal <noreply@example.com>")

if EMAIL_HOST:
    _default_email_backend = "django.core.mail.backends.smtp.EmailBackend"
else:
    _default_email_backend = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", _default_email_backend)


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("SQLITE_PATH", BASE_DIR / "db.sqlite3"),
        # Wait up to 20s for a write lock instead of erroring immediately.
        "OPTIONS": {"timeout": 20},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# collectstatic gathers files here; WhiteNoise serves them from here.
STATIC_ROOT = BASE_DIR / "staticfiles"


# Production hardening — only when DEBUG is off, so local dev over http still works.
# Assumes TLS terminates at a reverse proxy that sets X-Forwarded-Proto.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Comma-separated https origins for CSRF (e.g. https://lab.example.com).
    _csrf = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
    if _csrf:
        CSRF_TRUSTED_ORIGINS = _csrf.split(",")
